firebaseUrl: https://dropwizard-tutorial.firebaseio.com

jerseyClient:
  timeout: 10000ms
  connectionTimeout: 10000ms
  timeToLive: 1 hour
  cookiesEnabled: false
  maxConnections: 2048
  maxConnectionsPerRoute: 2048
  keepAlive: 0s
  minThreads: 1
  maxThreads: 1000
  gzipEnabled: false
  gzipEnabledForRequests: false

name: test
logging:
  level: INFO
  appenders:
  - type: console
    threshold: ALL
    logFormat: "PREFIX %-5p [%d{ISO8601}] [%X{reqId} %X{txnId}] %c: %m\n%ex"

server:
  applicationConnectors:
  - type: http
    port: 9999
  adminConnectors:
  - type: http
    port: 9991
  minThreads: 8
  maxThreads: 1024
  gzip:
    enabled: true
  requestLog:
    timeZone: IST
    appenders:
    - type: console
      logFormat: "%-5p [%d{ISO8601}] [%X{reqId} %X{txnId}] %replace(%c: %m){'\n', '\n '}%n%replace(%ex){'(?m)^(.)',' $1'}%nopex"

